### ISSUE TITLE
Generalize method sort_reviewer_by_review_volume_desc

### ISSUE THREAD

**Issue by adityajoshi1114** [adityajoshi1114/expertiza#8]
The method sort_reviewer_by_review_volume_desc should be generalized so that it can sort by any metric, not just review volume.  Other metrics might include number of suggestions, or number of suggestions + number of problems detected.  This method should not be counting the number of review rounds!  Since other places in the code will need to know the number of review rounds, it should be calculated somewhere else in the system.

**Comment by harshmauny** [comment]
I have assigned this issue to myself and made some changes in review_mapping_helper and also updated the respective tests. @adityajoshi1114  can you verify the changes and close this issue
